setlocal
set "NotDelayedFlag=!"
setlocal EnableDelayedExpansion

SET a=RandomPatrolGenerator\build\
SET b=.pbo
SET d=RandomPatrolGenerator\build\pbos\

FOR %%f IN (
RandomPatrolGeneratorAnizay.tem_anizay
RandomPatrolGeneratorAltis.Altis
RandomPatrolGeneratorChernarus.chernarus
RandomPatrolGeneratorChernarusWinter.Chernarus_Winter
RandomPatrolGeneratorChernarusSummer.chernarus_summer
RandomPatrolGeneratorEnoch.Enoch
RandomPatrolGeneratorFallujah.fallujah
RandomPatrolGeneratorKujari.tem_kujari
RandomPatrolGeneratorKunduz.Kunduz
RandomPatrolGeneratorMalden.Malden
RandomPatrolGeneratorRuha.ruha
RandomPatrolGeneratorSara.sara
RandomPatrolGeneratorStratis.Stratis
RandomPatrolGeneratorTakistan.takistan
RandomPatrolGeneratorTanoa.Tanoa
RandomPatrolGeneratorViro.vt7
RandomPatrolGeneratorRuha.ruha
RandomPatrolGeneratorWoodland_ACR.Woodland_ACR
RandomPatrolGeneratorporto.porto
RandomPatrolGeneratorMountains_ACR.Mountains_ACR
RandomPatrolGeneratorBootcamp_ACR.Bootcamp_ACR
RandomPatrolGeneratorZargabad.zargabad
RandomPatrolGeneratorI44_merderet_koth.I44_merderet_koth
RandomPatrolGeneratorI44_Merderet_V2.I44_Merderet_V2
RandomPatrolGeneratorI44_Omaha_V2.I44_Omaha_V2
RandomPatrolGeneratoriron_excelsior_Tobruk.iron_excelsior_Tobruk
RandomPatrolGeneratorSWU_Ardennes_1940.SWU_Ardennes_1940
RandomPatrolGeneratorSWU_Dunkirk_Bray_Dunes_1940.SWU_Dunkirk_Bray_Dunes_1940
RandomPatrolGeneratorSWU_Egypt_El_Alamein.SWU_Egypt_El_Alamein
RandomPatrolGeneratorHyde_Sark.Hyde_Sark
RandomPatrolGeneratorSWU_Greece_Pella_Region.SWU_Greece_Pella_Region
RandomPatrolGeneratorMCN_Neaville.MCN_Neaville
RandomPatrolGeneratorStaszow.Staszow
RandomPatrolGeneratorBaranow.Baranow
RandomPatrolGeneratorStaszowWinter.StaszowWinter
RandomPatrolGeneratorBaranowWinter.BaranowWinter
RandomPatrolGeneratorPanovoWinter.PanovoWinter
RandomPatrolGeneratorMCN_Neaville_Winter.MCN_Neaville_Winter
RandomPatrolGeneratorRockwall.Rockwall
RandomPatrolGeneratorsong_bin_tanh.song_bin_tanh
RandomPatrolGeneratorpsyfx_pht.psyfx_pht
RandomPatrolGeneratorpanthera3.panthera3
RandomPatrolGeneratorWL_Rosche.WL_Rosche
RandomPatrolGeneratorChernarus_2035.Chernarus_2035
RandomPatrolGeneratorlythium.lythium
RandomPatrolGeneratorIslaPera.IslaPera
RandomPatrolGeneratorFarabad.Farabad
RandomPatrolGeneratortem_suursaariv.tem_suursaariv
RandomPatrolGeneratorbrf_sumava.brf_sumava
RandomPatrolGeneratorSWU_Ardennes_1944_Winter.SWU_Ardennes_1944_Winter
RandomPatrolGeneratorWinthera3.Winthera3
RandomPatrolGeneratorColleville.Colleville
RandomPatrolGeneratorSWU_Aachen_Outskirts.SWU_Aachen_Outskirts
RandomPatrolGeneratorUtes.utes
RandomPatrolGeneratorcup_chernarus_A3.cup_chernarus_A3
RandomPatrolGeneratorVTF_Korsac.VTF_Korsac
RandomPatrolGeneratorjuju_sahatra.juju_sahatra
RandomPatrolGeneratorsws_mountain.sws_mountain
RandomPatrolGeneratorThirskW.ThirskW
RandomPatrolGeneratorK9S_Djalka.K9S_Djalka
RandomPatrolGeneratorkunduz_valley.kunduz_valley
RandomPatrolGeneratorjnd_dakpek_terrain.jnd_dakpek_terrain
RandomPatrolGeneratorRungSat.RungSat
RandomPatrolGeneratorjnd_balong.jnd_balong
RandomPatrolGeneratorDaKrong.DaKrong
RandomPatrolGeneratoryulakia.yulakia
RandomPatrolGeneratorvillage_normandy.village_normandy
RandomPatrolGeneratorjuju_orglandes.juju_orglandes
RandomPatrolGeneratorNorthTakistan.NorthTakistan
RandomPatrolGeneratormehland.mehland
RandomPatrolGeneratorfow_map_tarawa.fow_map_tarawa
RandomPatrolGeneratorswu_kokoda_map.swu_kokoda_map
RandomPatrolGeneratorfow_map_henderson.fow_map_henderson
RandomPatrolGeneratoriwojimaV2.iwojimaV2
) DO (
SET "c=%a%%%f"
xcopy /s "RandomPatrolGenerator\RandomPatrolGeneratorMalden.Malden" !c! /y /i
SET "e=%d%%%f%b%"
ECHO !c!
ECHO !e!
armake_w64.exe build -f -t DXT5 -p !c! !e!
)
pause